### ISSUE TITLE
OCR fails if it the background is not white

### ISSUE THREAD

**Issue by deanhouseholder** [RaptorX/WindowSnipping#4]
I have a lot of instances where I try to use OCR but it fails. This typically happens when the background color is not very close to white. If it's gray it typically fails. Also it never works if it's a dark theme with white text.

**Comment by RaptorX** [comment]
This is a known limitation of the Windows OCR engine that we are leveraging.
We have no way to control or fix this particular problem. :(

We are in the works of a tool that allows to do OCR with AI but it requires the user to have their token. So we are not releasing that tool for now.

**Comment by deanhouseholder** [comment]
Have you considered connecting to Google Vision API? https://cloud.google.com/vision/docs/ocr
Each person could generate their own token and add it to the app's .ini file.

**Comment by RaptorX** [comment]
We have a different tool for that: AI OCR. you can find it at [https://www.the-automator.com/AIOCR](https://www.the-automator.com/AIOCR)

**Comment by deanhouseholder** [comment]
Awesome! Purchased!
